/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AtButton {
        "color"?: string;
        "disabled"?: boolean;
        "fill"?: 'clear' | 'outline' | 'solid';
        "size"?: 'small' | 'default' | 'large';
        "type"?: 'submit' | 'reset' | 'button';
    }
}
export interface AtButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAtButtonElement;
}
declare global {
    interface HTMLAtButtonElement extends Components.AtButton, HTMLStencilElement {
    }
    var HTMLAtButtonElement: {
        prototype: HTMLAtButtonElement;
        new (): HTMLAtButtonElement;
    };
    interface HTMLElementTagNameMap {
        "at-button": HTMLAtButtonElement;
    }
}
declare namespace LocalJSX {
    interface AtButton {
        "color"?: string;
        "disabled"?: boolean;
        "fill"?: 'clear' | 'outline' | 'solid';
        "onButtonClick"?: (event: AtButtonCustomEvent<any>) => void;
        "size"?: 'small' | 'default' | 'large';
        "type"?: 'submit' | 'reset' | 'button';
    }
    interface IntrinsicElements {
        "at-button": AtButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "at-button": LocalJSX.AtButton & JSXBase.HTMLAttributes<HTMLAtButtonElement>;
        }
    }
}
