sonar.organization=juntossomosmais
sonar.projectKey=juntossomosmais_atomium_core

sonar.sources=src

sonar.test.inclusions=\
**/*.spec.js,\
**/*.spec.jsx,\
**/*.spec.ts,\
**/*.spec.tsx

sonar.coverage.exclusions=\
src/components/grid/col/col.tsx,\
output-target/*.spec.ts,\
output-target/index.ts
sonar.cpd.exclusions=\
src/components/textarea/**
sonar.exclusions=\
src/**/stories/**,\
src/global/**,\
src/components.d.ts,\
src/storybook-declarations.d.ts,\
src/typings.d.ts,\
src/index.ts

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
