sonar.organization=juntossomosmais
sonar.projectKey=juntossomosmais_atomium_token

sonar.sources=packages/tokens/src,packages/tokens/scripts

sonar.test.inclusions=\
packages/tokens/**/*.spec.js,\
packages/tokens/**/*.spec.jsx,\
packages/tokens/**/*.spec.ts,\
packages/tokens/**/*.spec.tsx

sonar.typescript.tsconfigPath=packages/tokens/tsconfig.json
sonar.javascript.lcov.reportPaths=packages/tokens/coverage/lcov.info
