sonar.organization=juntossomosmais
sonar.projectKey=juntossomosmais_atomium_token

sonar.sources=packages/tokens

sonar.test.inclusions=\
packages/tokens/scripts/**/*.spec.js,\
packages/tokens/scripts/**/*.spec.jsx,\
packages/tokens/scripts/**/*.spec.ts,\
packages/tokens/scripts/**/*.spec.tsx
sonar.exclusions=\
packages/tokens/node_modules/**,\
packages/tokens/**/dist/**,\
packages/tokens/.eslintrc.js,\
packages/tokens/jest.config.js,\
packages/tokens/**/*.spec.js,\
packages/tokens/**/*.spec.jsx,\
packages/tokens/**/*.spec.ts,\
packages/tokens/**/*.spec.tsx,\
packages/tokens/**/.md,\
packages/tokens/**/*.mdx,\
packages/tokens/stories/**,\
packages/tokens/.eslintrc.json,\
packages/tokens/.prettierrc.js,\
packages/tokens/jestconfig.js,\
packages/tokens/postcss.config.js,\
packages/tokens/tsconfig.json,\
packages/tokens/rollup.config.mjs,\
packages/tokens/rollup.config.js

sonar.typescript.tsconfigPath=packages/tokens/tsconfig.json
sonar.javascript.lcov.reportPaths=packages/tokens/coverage/lcov.info
