name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm install --legacy-peer-deps
          npm run docs:build

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: apps/docs/storybook-static
