name: Icons CDN Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'packages/icons/svg/**'

concurrency:
  group: icons-deploy
  cancel-in-progress: false

jobs:
  icons-deploy:
    name: Icons CDN Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies 🔧
        run: |
          echo "@juntossomosmais:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_ACTIONS }}" >> .npmrc
          pnpm install --frozen-lockfile

      - name: Build icons
        run: pnpm run icons:build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Sync AWS S3 bucket
        run: |
          aws s3 sync packages/icons/dist/svg s3://atomium/icons
