name: Deploy PR Previews

permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  issues: write
  packages: write
  pages: write
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.scss'
      - '**.mdx'

jobs:
  deploy-preview:
    concurrency: preview-${{ github.ref }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: List the state of node modules
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Docs 📚
        run: npm run docs:build
        continue-on-error: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy preview 🚀
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: apps/docs/storybook-static
