name: SonarCloud Scan

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.scss'
      - '**.mdx'
      - '**.properties'
      - '**.json'

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

concurrency:
  group: sonarcloud-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: ${{ !contains(github.event.head_commit.message, 'chore:') }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Restore Nx cache
        uses: actions/cache@v5
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-

      - name: Install dependencies 🔧
        run: |
          echo "@juntossomosmais:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_ACTIONS }}" >> .npmrc
          pnpm install --frozen-lockfile

      - name: Define test script to run
        id: define-script
        run: |
          if [[ "${{ github.event_name }}" == 'push' ]]; then
            echo "testScriptToRun=test:ci-merge" >> $GITHUB_OUTPUT
            echo "We gonna run test:ci-merge to you"
          elif [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "testScriptToRun=test:ci" >> $GITHUB_OUTPUT
            echo "We gonna run test:ci to you"
          fi

      - name: Run Tests 🧪
        run: pnpm run ${{ steps.define-script.outputs.testScriptToRun }}

      - name: Check coverage directory - Core
        run: |
          chmod +x ./.github/workflows/check-coverage.sh
          ./.github/workflows/check-coverage.sh core

      - name: Check coverage directory - Tokens
        run: |
          chmod +x ./.github/workflows/check-coverage.sh
          ./.github/workflows/check-coverage.sh tokens

      - name: SonarCloud Scan - Core 🚨
        if: env.COVERAGE_CORE == 'true'
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: packages/core/

      - name: SonarCloud Scan - Tokens 🚨
        if: env.COVERAGE_TOKENS == 'true'
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: -Dproject.settings=packages/tokens/sonar-project.properties
